package model;
// Generated 20/12/2012 05:46:46 by Hibernate Tools 3.2.1.GA

/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {
     private Long id;
     private String name;
     private String description;
     private String image;
     private User owner;

    public Album() {
    }

    public Album(String name, User owner) {
        this.name = name;
        this.owner = owner;
    }
    
    public Album(String name, String description, User owner) {
       this.name = name;
       this.description = description;
       this.owner = owner;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }
    
    public User getOwner() {
        return this.owner;
    }
    
    public void setOwner(User owner) {
        this.owner = owner;
    }
}


