package model;
// Generated 18/12/2012 03:05:14 by Hibernate Tools 3.2.1.GA



/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private Long id;
     private String nombre;
     private String descripcion;
     private long usuario;

    public Album() {
    }

	
    public Album(String nombre, long usuario) {
        this.nombre = nombre;
        this.usuario = usuario;
    }
    public Album(String nombre, String descripcion, long usuario) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.usuario = usuario;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public long getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(long usuario) {
        this.usuario = usuario;
    }




}


