package model;
// Generated 20/12/2012 05:46:46 by Hibernate Tools 3.2.1.GA



/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private Long id;
     private String name;
     private String description;
     private long owner;

    public Album() {
    }

	
    public Album(String name, long owner) {
        this.name = name;
        this.owner = owner;
    }
    public Album(String name, String description, long owner) {
       this.name = name;
       this.description = description;
       this.owner = owner;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getOwner() {
        return this.owner;
    }
    
    public void setOwner(long owner) {
        this.owner = owner;
    }




}


