package model;
// Generated 18/12/2012 03:05:14 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ComentariosMuro generated by hbm2java
 */
public class ComentariosMuro  implements java.io.Serializable {


     private Long id;
     private long origen;
     private long destino;
     private String cuerpo;
     private Date fecha;

    public ComentariosMuro() {
    }

    public ComentariosMuro(long origen, long destino, String cuerpo, Date fecha) {
       this.origen = origen;
       this.destino = destino;
       this.cuerpo = cuerpo;
       this.fecha = fecha;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(long origen) {
        this.origen = origen;
    }
    public long getDestino() {
        return this.destino;
    }
    
    public void setDestino(long destino) {
        this.destino = destino;
    }
    public String getCuerpo() {
        return this.cuerpo;
    }
    
    public void setCuerpo(String cuerpo) {
        this.cuerpo = cuerpo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


