package model;
// Generated 20/12/2012 05:46:46 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Long id;
//     private User origin;
     private User origin;
     private User destiny;
     private String type;
     private String body;
     private Date date;

    public Comment() {
    }

    public Comment(User origin, User destiny, String type, String body, Date date) {
       this.origin = origin;
       this.destiny = destiny;
       this.type = type;
       this.body = body;
       this.date = date;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public User getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(User origin) {
        this.origin = origin;
    }
    public User getDestiny() {
        return this.destiny;
    }
    
    public void setDestiny(User destiny) {
        this.destiny = destiny;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


