package model;
// Generated 18/12/2012 03:05:14 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Foto generated by hbm2java
 */
public class Foto  implements java.io.Serializable {


     private Long id;
     private byte[] foto;
     private String fotoUrl;
     private String descripcion;
     private Date fecha;
     private long album;

    public Foto() {
    }

	
    public Foto(Date fecha, long album) {
        this.fecha = fecha;
        this.album = album;
    }
    public Foto(byte[] foto, String fotoUrl, String descripcion, Date fecha, long album) {
       this.foto = foto;
       this.fotoUrl = fotoUrl;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.album = album;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getFotoUrl() {
        return this.fotoUrl;
    }
    
    public void setFotoUrl(String fotoUrl) {
        this.fotoUrl = fotoUrl;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public long getAlbum() {
        return this.album;
    }
    
    public void setAlbum(long album) {
        this.album = album;
    }




}


