package model;
// Generated 20/12/2012 05:46:46 by Hibernate Tools 3.2.1.GA



/**
 * Friendship generated by hbm2java
 */
public class Friendship  implements java.io.Serializable {


     private Long id;
     private String status;
     private long origin;
     private long destiny;

    public Friendship() {
    }

    public Friendship(String status, long origin, long destiny) {
       this.status = status;
       this.origin = origin;
       this.destiny = destiny;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public long getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(long origin) {
        this.origin = origin;
    }
    public long getDestiny() {
        return this.destiny;
    }
    
    public void setDestiny(long destiny) {
        this.destiny = destiny;
    }




}


