package model;
// Generated 20/12/2012 05:46:46 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Photo generated by hbm2java
 */
public class Photo  implements java.io.Serializable {


     private Long id;
     private String url;
     private String description;
     private Date date;
     private long album;

    public Photo() {
    }

	
    public Photo(String url, Date date, long album) {
        this.url = url;
        this.date = date;
        this.album = album;
    }
    public Photo(String url, String description, Date date, long album) {
       this.url = url;
       this.description = description;
       this.date = date;
       this.album = album;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public long getAlbum() {
        return this.album;
    }
    
    public void setAlbum(long album) {
        this.album = album;
    }




}


