package model;
// Generated 18/12/2012 03:05:14 by Hibernate Tools 3.2.1.GA



/**
 * SolicitudAmistad generated by hbm2java
 */
public class SolicitudAmistad  implements java.io.Serializable {


     private Long id;
     private Boolean accepted;
     private long origen;
     private long destino;

    public SolicitudAmistad() {
    }

	
    public SolicitudAmistad(long origen, long destino) {
        this.origen = origen;
        this.destino = destino;
    }
    public SolicitudAmistad(Boolean accepted, long origen, long destino) {
       this.accepted = accepted;
       this.origen = origen;
       this.destino = destino;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Boolean getAccepted() {
        return this.accepted;
    }
    
    public void setAccepted(Boolean accepted) {
        this.accepted = accepted;
    }
    public long getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(long origen) {
        this.origen = origen;
    }
    public long getDestino() {
        return this.destino;
    }
    
    public void setDestino(long destino) {
        this.destino = destino;
    }




}


