package model;
// Generated 20/12/2012 05:46:46 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private Long id;
    private String firstName;
    private String lastName;
    private String email;
    private String name;
    private String password;
    private String gender;
    private Date birth;
    private String photo;
    
    /* relations */
    @JsonBackReference private Set<User> friends = new HashSet<User>(0);
    @JsonBackReference private Set<Comment> commentsOnWall = new HashSet<Comment>(0);
    @JsonBackReference private Set<Album> albums = new HashSet<Album>(0);

    @Override
    public boolean equals(Object obj) {
        User other = (User) obj;
        return this.getId().equals(other.getId());
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }
    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getBirth() {
        return this.birth;
    }

    public void setBirth(Date birth) {
        this.birth = birth;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Set<User> getFriends() {
        return friends;
    }

    public void setFriends(Set<User> friends) {
        this.friends = friends;
    }

    public Set<Comment> getCommentsOnWall() {
        return commentsOnWall;
    }

    public void setCommentsOnWall(Set<Comment> commentsOnWall) {
        this.commentsOnWall = commentsOnWall;
    }

    public String getFullName() {
        return String.format("%s %s", firstName, lastName);
    }

    public Set<Album> getAlbums() {
        return albums;
    }

    public void setAlbums(Set<Album> albums) {
        this.albums = albums;
    }
}
