package model;
// Generated 18/12/2012 03:05:14 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long id;
     private String nombre;
     private String apellido;
     private String email;
     private String user;
     private String password;
     private boolean genero;
     private Date nacimiento;
     private String imagenPerfil;

    public Usuario() {
    }

    public Usuario(String nombre, String apellido, String email, String user, 
            String password, boolean genero, Date nacimiento,
            String imagenPerfil) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.user = user;
       this.password = password;
       this.genero = genero;
       this.nacimiento = nacimiento;
       this.imagenPerfil = imagenPerfil;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isGenero() {
        return this.genero;
    }
    
    public void setGenero(boolean genero) {
        this.genero = genero;
    }
    public Date getNacimiento() {
        return this.nacimiento;
    }
    
    public void setNacimiento(Date nacimiento) {
        this.nacimiento = nacimiento;
    }
    public String getImagenPerfil() {
        return this.imagenPerfil;
    }
    
    public void setImagenPerfil(String imagenPerfil) {
        this.imagenPerfil = imagenPerfil;
    }




}


